### ISSUE TITLE
Qt6 Graph issue incomplete rendering

### ISSUE THREAD

**Issue by Madrich** [Sonnentierchen/Qt3D-OfflineRenderer#9]
In order the frame graph should work correctly, make the render capture node as a the last child. In this example it must be the child of cameraSelector.
Otherwise the rendering can be incomplete and the rendering produces strange artefacts.

**Comment by Madrich** [comment]
Anyway thanks for the example. However I observe slow rendering of about 60ms per frame even for very simple scenes. There must be a issue with internal threading of the aspect engine I guess. Would be nice if somebody can investigate it.

**Comment by florianblume** [comment]
Thanks for your comments. Are you sure about that the capture node needs to be a child of cameraSelector? Did you get artifacts? From my understanding, Qt3D executes each branch -> leaf node after the other. First, it executes the clear buffers, then drawing using the camera selector and, since it's the third branch being a child of target selector, captures the drawn content.

Regarding the 60ms per frame, I had a lot of issues with performance with Qt3D, so I'm assuming it's on their end. Drawing to a texture and drawing that texture on a quad should not take that long, I agree. The texture is also not moved from GPU memory.

**Comment by Madrich** [comment]
I read in a blog to apply it at the end. Therefore I made the test and it worked perfectly. To verify I tried other places in the frame graph without success.
I agree to the performance comment. Maybe it's the setting to manual render trigger in the engine. I wonder too. Could be analyzed with a profiler maybe.

**Comment by florianblume** [comment]
I'll wait for this one merge request that is still open where I asked the guy a couple of questions. He changed the position of the capture, too. Regarding the performance thing, yes that's doable but out of my scope ;) But of course, if you find something out let me know and feel free to open a merge request! Closing this issue for now.
